services:
  database:
      build:
        context: ./backend
        dockerfile: Dockerfile.database
      image: viniciusnypdev/campus-rater-database
      restart: always
      env_file: ./.env
      environment:
        - POSTGRES_DB=${DB_NAME} 
        - POSTGRES_USER=${DB_USER}  
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      volumes:
        - database_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - campus-rater-network

  server:
    build: "./backend"
    restart: always
    depends_on:
      - database
    env_file: ./backend/.env
    environment:
      - DB_HOST=database 
      - DB_PORT=5432
      - ENVIRONMENT=local
      - SERVER_PORT=80
      - CLIENT_HOST=client
      - CLIENT_PORT=80
    ports:
      - "5000:80"
    networks:
      - campus-rater-network
    image: viniciusnypdev/campus-rater-server

  client: 
    build: ./frontend
    depends_on:
      - server
    env_file: "./frontend/.env"
    environment:
      - VITE_SERVER_HOST=server
      - VITE_SERVER_PORT=80
      - VITE_CLIENT_PORT=80
      - VITE_CLIENT_HOST=client
      - VITE_ENVIRONMENT=dev
    ports:
      - "8000:80"
    networks:
      - campus-rater-network
    image: viniciusnypdev/campus-rater-client

volumes:
  database_data:

networks:
  campus-rater-network:
    driver: bridge
    