services:
  database:
      image: postgres:16-bullseye
      restart: always
      env_file: ./backend/.env
      environment:
        - POSTGRES_DB=${DB_NAME} 
        - POSTGRES_USER=${DB_USER}  
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      volumes:
        - database_data:/var/lib/postgresql/data

  server:
    build: "./backend"
    restart: always
    depends_on:
      - database
    env_file: ./backend/.env
    environment:
      - DB_HOST=database 
      - DB_PORT=5432
      - ENVIRONMENT=prod
      - APP_PORT=80
      - CLIENT_HOST=client
      - CLIENT_PORT=80


  client: 
    build: ./frontend
    depends_on:
      - server
    env_file: "./frontend/.env"
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=80
      - APP_PORT=80
      - ENVIRONMENT=prod

volumes:
  database_data: